namespace Reflecta
{
    public enum MoCapMixamoFacialExpression
    {
        Unknown = -1,

        Blink_Left = 0,
        Blink_Right = 1,
        BrowsDown_Left = 2,
        BrowsDown_Right = 3,
        BrowsIn_Left = 4,
        BrowsIn_Right = 5,
        BrowsOuterLower_Left = 6,
        BrowsOuterLower_Right = 7,
        BrowsUp_Left = 8,
        BrowsUp_Right = 9,
        CheekPuff_Left = 10,
        CheekPuff_Right = 11,
        EyesWide_Left = 12,
        EyesWide_Right = 13,
        Frown_Left = 14,
        Frown_Right = 15,
        JawBackward = 16,
        JawForeward = 17,
        JawRotateY_Left = 18,
        JawRotateY_Right = 19,
        JawRotateZ_Left = 20,
        JawRotateZ_Right = 21,
        Jaw_Down = 22,
        Jaw_Left = 23,
        Jaw_Right = 24,
        Jaw_Up = 25,
        LowerLipDown_Left = 26,
        LowerLipDown_Right = 27,
        LowerLipIn = 28,
        LowerLipOut = 29,
        Midmouth_Left = 30,
        Midmouth_Right = 31,
        MouthDown = 32,
        MouthNarrow_Left = 33,
        MouthNarrow_Right = 34,
        MouthOpen = 35,
        MouthUp = 36,
        MouthWhistle_NarrowAdjust_Left = 37,
        MouthWhistle_NarrowAdjust_Right = 38,
        NoseScrunch_Left = 39,
        NoseScrunch_Right = 40,
        Smile_Left = 41,
        Smile_Right = 42,
        Squint_Left = 43,
        Squint_Right = 44,
        TongueUp = 45,
        UpperLipIn = 46,
        UpperLipOut = 47,
        UpperLipUp_Left = 48,
        UpperLipUp_Right = 49,

        LastBlendShape = 50
    }
}